name = "api-proxy"
main = ".output/server/index.mjs"
assets = { binding = "ASSETS", directory = "../public" }
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]

[vars]
HOMEPAGE_ENABLE = "true"
PROXY_GEMINI_TARGET = "https://generativelanguage.googleapis.com"
PROXY_OPENAI_TARGET = "https://api.openai.com"
PROXY_ANTHROPIC_TARGET = "https://api.anthropic.com"
